local user = "default"

require((user) .. '.options')
require((user) .. '.mappings')
require((user) .. '.packer')
require((user) .. '.lsp')
require((user) .. '.trouble')
require((user) .. '.treesitter')
require((user) .. '.cmp')
require((user) .. '.telescope')
require((user) .. '.lightspeed')
require((user) .. '.autopairs')
require((user) .. '.statusline')
require((user) .. '.colorscheme')
require((user) .. '.lsp_signature')
require((user) .. '.indents')
